# Generated by Django 4.2.4 on 2023-09-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='thumbnail/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('owner_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('floor_plan', models.FileField(blank=True, default='', null=True, upload_to='floorplan/')),
                ('whatsapp_no', models.IntegerField()),
                ('nearby_place', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('features', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('property_type', models.CharField(blank=True, choices=[('', 'Select an option'), ('Houses', 'Houses'), ('Apartment', 'Apartment'), ('Villas', 'Villas'), ('Commercial', 'Commercial'), ('Garage', 'Garage')], max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Select an option'), ('For Sale', 'For Sale')], max_length=40, null=True)),
                ('bedrooms', models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('More than 5', 'More than 5')], max_length=40, null=True)),
                ('bathrooms', models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('More than 5', 'More than 5')], max_length=40, null=True)),
                ('rooms', models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('More than 8', 'More than 8')], max_length=40, null=True)),
                ('state', models.CharField(blank=True, choices=[('', 'Select an option'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=40, null=True)),
                ('garage', models.CharField(blank=True, choices=[('', 'Select an option'), ('0', '0'), ('1', '1'), ('2', '2'), ('More than 2', 'More than 2')], max_length=40, null=True)),
                ('major_road', models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True)),
                ('near_hospital', models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True)),
                ('near_supermarket', models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True)),
                ('bulding_age', models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than one year', 'Less than one year'), ('1-5 Year', '1-5 Year'), ('5-10 Years', '5-10 Years'), ('More than 10 Years', 'More than 10 Years')], max_length=40, null=True)),
                ('floor', models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=40, null=True)),
                ('floor_no', models.CharField(blank=True, choices=[('', 'Select an option'), ('Ground Floor', 'Ground Floor'), ('1 Floor', '1 Floor'), ('2 Floor', '2 Floor'), ('3 Floor', '3 Floor'), ('4 Floor', '4 Floor'), ('5 Floor', '5 Floor'), ('6 Floor', '6 Floor'), ('7 Floor', '7 Floor'), ('8 Floor', '8 Floor'), ('9 Floor', '9 Floor'), ('10 Floor', '10 Floor'), ('11 Floor', '11 Floor'), ('12 Floor', '12 Floor'), ('13 Floor', '13 Floor'), ('14 Floor', '14 Floor'), ('15 Floor', '15 Floor'), ('16 Floor', '16 Floor'), ('17 Floor', '17 Floor'), ('18 Floor', '18 Floor'), ('19 Floor', '19 Floor'), ('20 Floor', '20 Floor'), ('21 Floor', '21 Floor'), ('22 Floor', '22 Floor'), ('23 Floor', '23 Floor'), ('24 Floor', '24 Floor'), ('25 Floor', '25 Floor'), ('26 Floor', '26 Floor'), ('27 Floor', '27 Floor'), ('28 Floor', '28 Floor'), ('29 Floor', '29 Floor'), ('30 Floor', '30 Floor'), ('31 Floor', '31 Floor'), ('32 Floor', '32 Floor'), ('33 Floor', '33 Floor'), ('34 Floor', '34 Floor'), ('35 Floor', '35 Floor'), ('36 Floor', '36 Floor'), ('37 Floor', '37 Floor'), ('38 Floor', '38 Floor'), ('39 Floor', '39 Floor'), ('40 Floor', '40 Floor'), ('41 Floor', '41 Floor'), ('42 Floor', '42 Floor'), ('43 Floor', '43 Floor'), ('44 Floor', '44 Floor'), ('45 Floor', '45 Floor'), ('46 Floor', '46 Floor'), ('47 Floor', '47 Floor'), ('48 Floor', '48 Floor'), ('49 Floor', '49 Floor'), ('50 Floor', '50 Floor'), ('51 Floor', '51 Floor'), ('52 Floor', '52 Floor'), ('53 Floor', '53 Floor'), ('54 Floor', '54 Floor'), ('55 Floor', '55 Floor'), ('56 Floor', '56 Floor'), ('57 Floor', '57 Floor'), ('58 Floor', '58 Floor'), ('59 Floor', '59 Floor'), ('60 Floor', '60 Floor'), ('61 Floor', '61 Floor'), ('62 Floor', '62 Floor'), ('63 Floor', '63 Floor'), ('64 Floor', '64 Floor'), ('65 Floor', '65 Floor'), ('66 Floor', '66 Floor'), ('67 Floor', '67 Floor'), ('68 Floor', '68 Floor'), ('69 Floor', '69 Floor'), ('70 Floor', '70 Floor'), ('71 Floor', '71 Floor'), ('72 Floor', '72 Floor'), ('73 Floor', '73 Floor'), ('74 Floor', '74 Floor'), ('75 Floor', '75 Floor'), ('76 Floor', '76 Floor'), ('77 Floor', '77 Floor'), ('78 Floor', '78 Floor'), ('79 Floor', '79 Floor'), ('80 Floor', '80 Floor'), ('81 Floor', '81 Floor'), ('82 Floor', '82 Floor'), ('83 Floor', '83 Floor'), ('84 Floor', '84 Floor'), ('85 Floor', '85 Floor'), ('86 Floor', '86 Floor'), ('87 Floor', '87 Floor'), ('88 Floor', '88 Floor'), ('89 Floor', '89 Floor'), ('90 Floor', '90 Floor')], max_length=40, null=True)),
                ('last_renovated', models.CharField(blank=True, choices=[('', 'Select an option'), ('Not Yet Renovated', 'Not Yet Renovated'), ('1-5 Year Before', '1-5 Year Before'), ('5-10 Years Before', '5-10 Years Before'), ('More than 10 Years Before', 'More than 10 Years Before')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.property')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
