# Generated by Django 4.2.4 on 2023-09-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='userprofile',
        ),
    ]
