# Generated by Django 4.2.4 on 2023-09-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_customuser_last_logout'),
        ('Customer', '0002_rename_user_feedback_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.userprofile'),
        ),
    ]
