# Generated by Django 4.2.4 on 2023-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bulding_age',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1 Years', '0-1 Years'), ('2-5 Years ', '2-5 Years'), ('6-10 Years', '6-10 Years'), ('11-15 Years', '11-15 Years'), ('16-20 Years', '16-20 Years'), ('More than 10 Years', 'More than 10 Years')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='major_road',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1 Kilometer', '0-1 Kilometer'), ('2-5 Kilometer near', '2-5 Kilometer'), ('6-10 Kilometer', '6-10 Kilometer'), ('11-15 Kilometer', '11-15 Kilometer'), ('16-20 Kilometer', '16-20 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_hospital',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1 Kilometer', '0-1 Kilometer'), ('2-5 Kilometer near', '2-5 Kilometer'), ('6-10 Kilometer', '6-10 Kilometer'), ('11-15 Kilometer', '11-15 Kilometer'), ('16-20 Kilometer', '16-20 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_supermarket',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1 Kilometer', '0-1 Kilometer'), ('2-5 Kilometer near', '2-5 Kilometer'), ('6-10 Kilometer', '6-10 Kilometer'), ('11-15 Kilometer', '11-15 Kilometer'), ('16-20 Kilometer', '16-20 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
    ]
