# Generated by Django 4.2.4 on 2023-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_property_bulding_age_alter_property_major_road_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='major_road',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_hospital',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_supermarket',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
    ]
