# Generated by Django 4.2.4 on 2023-10-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bulding_age',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5 ', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Years', 'More than 10 Years')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_no',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('0', 'Ground Floor'), ('1', '1 Floor'), ('2', '2 Floor'), ('3', '3 Floor'), ('4', '4 Floor'), ('5', '5 Floor'), ('6', '6 Floor'), ('7', '7 Floor'), ('8', '8 Floor'), ('9', '9 Floor'), ('10', '10 Floor'), ('11', '11 Floor'), ('12', '12 Floor'), ('13', '13 Floor'), ('14', '14 Floor'), ('15', '15 Floor'), ('16', '16 Floor'), ('17', '17 Floor'), ('18', '18 Floor'), ('19', '19 Floor'), ('20', '20 Floor'), ('21', '21 Floor'), ('22', '22 Floor'), ('23', '23 Floor'), ('24', '24 Floor'), ('25', '25 Floor'), ('26', '26 Floor'), ('27', '27 Floor'), ('28', '28 Floor'), ('29', '29 Floor'), ('30', '30 Floor'), ('31', '31 Floor'), ('32', '32 Floor'), ('33', '33 Floor'), ('34', '34 Floor'), ('35', '35 Floor'), ('36', '36 Floor'), ('37', '37 Floor'), ('38', '38 Floor'), ('39', '39 Floor'), ('40', '40 Floor'), ('41', '41 Floor'), ('42', '42 Floor'), ('43', '43 Floor'), ('44', '44 Floor'), ('45', '45 Floor'), ('46', '46 Floor'), ('47', '47 Floor'), ('48', '48 Floor'), ('49', '49 Floor'), ('50', '50 Floor'), ('51', '51 Floor'), ('52', '52 Floor'), ('53', '53 Floor'), ('54', '54 Floor'), ('55', '55 Floor'), ('56', '56 Floor'), ('57', '57 Floor'), ('58', '58 Floor'), ('59', '59 Floor'), ('60', '60 Floor'), ('61', '61 Floor'), ('62', '62 Floor'), ('63', '63 Floor'), ('64', '64 Floor'), ('65', '65 Floor'), ('66', '66 Floor'), ('67', '67 Floor'), ('68', '68 Floor'), ('69', '69 Floor'), ('70', '70 Floor'), ('71', '71 Floor'), ('72', '72 Floor'), ('73', '73 Floor'), ('74', '74 Floor'), ('75', '75 Floor'), ('76', '76 Floor'), ('77', '77 Floor'), ('78', '78 Floor'), ('79', '79 Floor'), ('80', '80 Floor'), ('81', '81 Floor'), ('82', '82 Floor'), ('83', '83 Floor'), ('84', '84 Floor'), ('85', '85 Floor'), ('86', '86 Floor'), ('87', '87 Floor'), ('88', '88 Floor'), ('89', '89 Floor'), ('90', '90 Floor')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_renovated',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('Not Yet Renovated', 'Not Yet Renovated'), ('1-5', '1-5 Year Before'), ('5-10', '5-10'), ('More than 10 Years Before', 'More than 10 Years Before')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='major_road',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_hospital',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_supermarket',
            field=models.IntegerField(blank=True, choices=[('', 'Select an option'), ('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('More than 10 Kilometer', 'More than 10 Kilometer')], null=True),
        ),
    ]
