# Generated by Django 4.2.4 on 2023-10-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='days_to_sell',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tips',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_duration_tips',
            field=models.TextField(default=''),
        ),
    ]
