# Generated by Django 4.2.7 on 2024-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_loanapplicant_nominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicant',
            name='employment_type',
            field=models.CharField(choices=[('Self Employed', 'Self Employed'), ('Business', 'Business'), ('Salaried', 'Salaried')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
