# Generated by Django 4.2.7 on 2024-02-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_alter_loanapplicant_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
