# Generated by Django 4.2.7 on 2024-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0025_compareproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Agent')], default=1),
        ),
    ]
