# Generated by Django 4.2.7 on 2024-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0028_alter_property_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinteriors',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
