# Generated by Django 4.2.7 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0029_homeinteriors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinteriors',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
    ]
