# Generated by Django 4.2.7 on 2024-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0031_feedback_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicant',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
    ]
