# Generated by Django 4.2.4 on 2023-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(blank=True, choices=[('BASIC', 'BASIC'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validity', models.CharField(blank=True, choices=[('1 MONTH', '1 MONTH'), ('2 MONTH', '2 MONTH'), ('3 MONTH', '3 MONTH'), ('4 MONTH', '4 MONTH'), ('5 MONTH', '5 MONTH'), ('6 MONTH', '6 MONTH'), ('7 MONTH', '7 MONTH'), ('8 MONTH', '8 MONTH'), ('9 MONTH', '9 MONTH'), ('10 MONTH', '10 MONTH'), ('11 MONTH', '11 MONTH'), ('12 MONTH', '12 MONTH')], max_length=40, null=True)),
                ('features', models.ManyToManyField(to='FindMyNestApp.feature')),
            ],
        ),
    ]
