# Generated by Django 4.2.4 on 2023-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_customuser_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_logout',
        ),
    ]
