# Generated by Django 4.2.7 on 2024-01-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_customuser_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Agent')], default=1, null=True),
        ),
    ]
