# Generated by Django 4.2.7 on 2024-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_userprofile_profile_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_editable',
            field=models.BooleanField(default=False),
        ),
    ]
