# Generated by Django 4.2.7 on 2024-01-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_userprofile_profile_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_editable',
            field=models.BooleanField(default=True),
        ),
    ]
