# Generated by Django 4.2.7 on 2024-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_agentprofile_view_count_agentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='working_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
