# Generated by Django 4.2.7 on 2024-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_executiveprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Agent'), (4, 'Executive'), (4, 'Editor')], default=1, null=True),
        ),
    ]
